[theme]
name = "Monokai Pro"

[theme.base]
white = "#fcfcfa"
black = "#19181a"
grey = "#5b595c"
blue = "#78dce8"
red = "#ff6188"
yellow = "#ffd866"
orange = "#fc9867"
green = "#a9dc76"
purple = "#ab9df2"
cyan = "#78dce8"
magenta = "#ab9df2"

[theme.syntax]
"comment" = "$grey"
"constant" = "$yellow"
"type" = "$yellow"
"typeAlias" = "$yellow"
"number" = "$yellow"
"enum" = "$blue"
"struct" = "$blue"
"structure" = "$blue"
"interface" = "$blue"
"attribute" = "$yellow"
"constructor" = "$yellow"
"function" = "$green"
"method" = "$green"
"function.method" = "$blue"
"keyword" = "$red"
"selfKeyword" = "$white"
"field" = "$red"
"property" = "$white"
"enumMember" = "$green"
"enum-member" = "$green"
"variable.other.member" = "$purple"
"string" = "$green"
"type.builtin" = "$cyan"
"builtinType" = "$cyan"
"escape" = "$cyan"
"embedded" = "$cyan"

[theme.ui]
"lapce.active_tab" = "$black"
"lapce.inactive_tab" = "$grey"
"lapce.error" = "$red"
"lapce.warn" = "$yellow"
"lapce.dropdown_shadow" = "#000000"
"lapce.border" = "#000000"
"lapce.scroll_bar" = "$grey"


"editor.background" = "$black"
"editor.foreground" = "$white"
"editor.dim" = "$gray"
"editor.focus" = "$gray"
"editor.caret" = "#939293"
"editor.selection" = "#2d2a2e"
"editor.current_line" = "#221f22"
"editor.link" = "$cyan"

"inlay_hint.foreground" = "$white"
"inlay_hint.background" = "#528bFF88"

"error_lens.error.foreground" = "$red"
"error_lens.error.background" = "#E06C7520"
"error_lens.warning.foreground" = "$yellow"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.other.foreground" = "#5C6370"
"error_lens.other.background" = "#5C637020"

"source_control.added" = "#50A14F32"
"source_control.removed" = "#FF526632"
"source_control.modified" = "#0184BC32"

"palette.background" = "$black"
"palette.current" = "#2C313A"

"completion.background" = "#21252B"
"completion.current" = "#2C313A"

"hover.background" = "#403e41"

"activity.background" = "#21252B"
"activity.current" = "$black"

"panel.background" = "$black"
"panel.current" = "$gray"
"panel.hovered" = "$gray"

"status.background" = "#21252B"
"status.modal.normal" = "$blue"
"status.modal.insert" = "$red"
"status.modal.visual" = "$yellow"
"status.modal.terminal" = "$purple"

"markdown.blockquote" = "#898989"

"terminal.cursor" = "$white"
"terminal.foreground" = "$white"
"terminal.background" = "$black"
"terminal.white" = "$white"
"terminal.black" = "$black"
"terminal.red" = "$red"
"terminal.blue" = "$blue"
"terminal.green" = "$green"
"terminal.yellow" = "$yellow"
"terminal.cyan" = "$cyan"
"terminal.magenta" = "$magenta"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_red" = "$red"
"terminal.bright_blue" = "$blue"
"terminal.bright_green" = "$green"
"terminal.bright_yellow" = "$yellow"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_black" = "#545862"